Fixing missing settings

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -92,30 +92,6 @@ workflows:
         - project_location: "$PROJECT_LOCATION"
     - sign-apk@1: {}
     - certificate-and-profile-installer@1: {}
-    - script@1:
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -e
-            # debug log
-            set -x
-
-            # write your script here
-            echo "Hello World!"
-
-            # or run a script from your repository, like:
-            # bash ./path/to/script.sh
-            # not just bash, e.g.:
-            # ruby ./path/to/script.rb
-            cd ./ && npm run build:ios
-    - cocoapods-install@2.2: {}
-    - xcode-archive@4.2:
-        inputs:
-        - project_path: "$BITRISE_PROJECT_PATH"
-        - scheme: "$BITRISE_SCHEME"
-        - distribution_method: "$BITRISE_DISTRIBUTION_METHOD"
-        - configuration: Release
     - deploy-to-bitrise-io@2: {}
   deploy:
     description: "## Configure Android part of the deploy workflow\n\nTo generate
@@ -205,6 +181,7 @@ workflows:
     - activate-ssh-key@4:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@6: {}
+    - cache-pull@2.5: {}
     - yarn@0:
         inputs:
         - command: install
@@ -227,6 +204,68 @@ workflows:
             # ruby ./path/to/script.rb
             cd ./ && npm run build:ios
     - cocoapods-install@2.2: {}
+    - xcode-archive@4.2:
+        inputs:
+        - project_path: "$BITRISE_PROJECT_PATH"
+        - scheme: "$BITRISE_SCHEME"
+        - distribution_method: "$BITRISE_DISTRIBUTION_METHOD"
+        - configuration: Release
+    - deploy-to-bitrise-io@2: {}
+  ios-clone:
+    description: "## Configure Android part of the deploy workflow\n\nTo generate
+      a signed APK:\n\n1. Open the **Workflow** tab of your project on Bitrise.io\n1.
+      Add **Sign APK step right after Android Build step**\n1. Click on **Code Signing**
+      tab\n1. Find the **ANDROID KEYSTORE FILE** section\n1. Click or drop your file
+      on the upload file field\n1. Fill the displayed 3 input fields:\n1. **Keystore
+      password**\n1. **Keystore alias**\n1. **Private key password**\n1. Click on
+      **[Save metadata]** button\n\nThat's it! From now on, **Sign APK** step will
+      receive your uploaded files.\n\n## Configure iOS part of the deploy workflow\n\nTo
+      generate IPA:\n\n1. Open the **Workflow** tab of your project on Bitrise.io\n1.
+      Click on **Code Signing** tab\n1. Find the **PROVISIONING PROFILE** section\n1.
+      Click or drop your file on the upload file field\n1. Find the **CODE SIGNING
+      IDENTITY** section\n1. Click or drop your file on the upload file field\n1.
+      Click on **Workflows** tab\n1. Select deploy workflow\n1. Select **Xcode Archive
+      & Export for iOS** step\n1. Open **Force Build Settings** input group\n1. Specify
+      codesign settings\nSet **Force code signing with Development Team**, **Force
+      code signing with Code Signing Identity**  \nand **Force code signing with Provisioning
+      Profile** inputs regarding to the uploaded codesigning files\n1. Specify manual
+      codesign style\nIf the codesigning files, are generated manually on the Apple
+      Developer Portal,  \nyou need to explicitly specify to use manual coedsign settings
+      \ \n(as ejected rn projects have xcode managed codesigning turned on).  \nTo
+      do so, add 'CODE_SIGN_STYLE=\"Manual\"' to 'Additional options for xcodebuild
+      call' input\n\n## To run this workflow\n\nIf you want to run this workflow manually:\n\n1.
+      Open the app's build list page\n2. Click on **[Start/Schedule a Build]** button\n3.
+      Select **deploy** in **Workflow** dropdown input\n4. Click **[Start Build]**
+      button\n\nOr if you need this workflow to be started by a GIT event:\n\n1. Click
+      on **Triggers** tab\n2. Setup your desired event (push/tag/pull) and select
+      **deploy** workflow\n3. Click on **[Done]** and then **[Save]** buttons\n\nThe
+      next change in your repository that matches any of your trigger map event will
+      start **deploy** workflow.\n"
+    steps:
+    - activate-ssh-key@4:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone@6: {}
+    - yarn@0:
+        inputs:
+        - command: install
+    - certificate-and-profile-installer@1: {}
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # write your script here
+            echo "Hello World!"
+
+            # or run a script from your repository, like:
+            # bash ./path/to/script.sh
+            # not just bash, e.g.:
+            # ruby ./path/to/script.rb
+            cd ./ && npm run build:ios
     - xcode-archive@4.2:
         inputs:
         - project_path: "$BITRISE_PROJECT_PATH"
